fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
index:
    path: /
    controller: App\Controller\DefaultController::index


api_random:
    type: rest
    prefix: /api/random
    resource: App\Controller\Api\ApiRandomController
    options:
        expose: true

api_shortener:
    type: rest
    prefix: /api/shortener
    resource: App\Controller\Api\ApiShortenerController
    options:
        expose: true
